# SSK REDIRECT

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
          




kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-payment
  namespace: payment
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /payment_resource/
    appgw.ingress.kubernetes.io/connection-draining: 'true'
    appgw.ingress.kubernetes.io/connection-draining-timeout: '30'
    appgw.ingress.kubernetes.io/cookie-based-affinity: 'true'
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - hosts:
        - xxx.xxx.xxx.azure.com
      secretName: aks-ingress-cert
  rules:
    - host: xxx.xxx.xxx.azure.com
      http:
        paths:
          - path: /payment/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: payment-svc
                port:
                  number: 80