apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-hpa
  name: nginx-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hpa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-hpa
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 8888
        resources: {}
status: {}
