---
- name: Install nfs-util with RedHat
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install nfs-util on Debian
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Config nfs server
  include: nfs-server.yml
  when: nfs_type == 'server'
  tags: nfs-server

- name: Config nfs client
  include: nfs-client.yml
  when: nfs_type == 'client'
  tags: nfs-client
