---
- name: Copy variable ip nfs server
  set_fact:
    nfs_server_ip: "{{ hostvars['pc1']['ansible_ssh_host'] }}"

- name: Create folder mounted
  file:
    path: '{{ item.mounted }}'
    state: directory
    mode: '{{ folder_mounted_permission }}'
    owner: root
    group: root
  loop: '{{ folder_mounted }}'

- name: Mount NFS
  mount:
    src: '{{ nfs_server_ip }}:{{ item.sharing }}'
    path: '{{ item.mounted }}'
    fstype: nfs
    state: mounted
  loop: '{{ folder_mounted }}'
