---
- name: HELM create folder setup
  file:
    path: /setup
    state: directory
    owner: root
    group: root
    mode: '0755'  

- name: HELM Download quick install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /setup/get-helm-3.sh
    mode: '0750'

- name: HELM Install form quick script
  shell: |
    PATH=$PATH:/usr/local/bin/
    /setup/get-helm-3.sh


#For Centos
- name: HELM install bash completion RedHat
  yum:
    name: bash-completion
    state: present
  when: ansible_os_family == "RedHat"

- name: HELM install bash completion Debian
  apt:
    name: bash-completion
    state: present
  when: ansible_os_family == "Debian"

  
- name: HELM Import bash completion 
  shell: |
    PATH=$PATH:/usr/local/bin/
    helm completion bash > /etc/bash_completion.d/helm