---
- name: HELM create folder setup
  file:
    path: /setup/kubecolor
    state: directory
    owner: root
    group: root
    mode: '0755' 

- name: KUBECOLOR Download file
  get_url:
    url: https://github.com/hidetatz/kubecolor/releases/download/v0.0.20/kubecolor_0.0.20_Linux_x86_64.tar.gz
    dest: /setup/kubecolor_0.0.20_Linux_x86_64.tar.gz
    mode: '0644'
 
- name: KUBECOLOR Extract foo.tgz into /var/lib/foo
  unarchive:
    src: /setup/kubecolor_0.0.20_Linux_x86_64.tar.gz
    dest: /setup/kubecolor/

- name: KUBECOLOR Copy file to /usr/bin/
  shell: |
    chmod 755 /setup/kubecolor/kubecolor
    cp -rp /setup/kubecolor/kubecolor /usr/bin/
