---
# tasks file for roles/basic-install-k8s
- name: helm install
  include: helm.yml
  become: true
  when: install == "helm"
  tags: helm


- name: Kubecolor install
  include: kubecolor.yml
  become: true
  when: install == "kubecolor"
  tags: kubecolor


- name: Kustomize install
  include: kustomize.yml
  become: true
  when: install == "kustomize"
  tags: kustomize
