---
# tasks file for roles/basic-install-k8s
- name: helm install
  include: helm.yml
  become: true
  when: helm_install
  tags: helm


- name: Kubecolor install
  include: kubecolor.yml
  become: true
  when: kubecolor_install
  tags: kubecolor
