---
- name: Create folder Sharing
  file:
    path: '{{ item }}'
    state: directory
    mode: '{{ folder_sharing_permission }}'
    owner: root
    group: root
  loop: '{{ folder_sharing }}'

- name: Add export
  lineinfile:
    path: /etc/exports
    regexp: '^{{ item }}'
    line: '{{ item }} *(rw,sync,no_root_squash,no_subtree_check)'
  loop: '{{ folder_sharing }}'

- name: Start nfs
  systemd:
    name: nfs
    state: restarted

- name: Add auto start nfs server
  systemd:
    name: nfs
    enabled: yes
    masked: no


- name: Report exportfs
  shell: 'exportfs -a'
