apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/
  - monitoring/
  - nginx/

commonLabels:
  sandbox: dev

# Transform all postgres images to mysql
images:
  - name: postgres
    newName: mysql