apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-schedule
  name: nginx-schedule
spec:
  containers:
  - image: nginx:alpine
    name: nginx-schedule
    resources: {}
  nodeSelector:
    vga: enable_vga
