apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  index.html: |
    Xinchao!!!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: configmaptestapp
        image: nginx:alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: data-volume
        ports:
        - containerPort: 80
      volumes:
        - name: data-volume
          configMap:
            name: test-config
